version: '3'
services:
  node1:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .
    # Mapping of container port to host
    ports:
      - "8080:8080"
    # expose ports without publishing them to the host machine
    expose:
      - 8080
    links:
      - memcached
    depends_on:
      - memcached
  node2:
    build: .
    ports:
      - "8081:8080"
    expose:
      - 8080
    links:
      - memcached
    depends_on:
      - memcached
  lb:
    # image to fetch from docker hub
    build:
      context: ./haproxy
      dockerfile: Dockerfile-haproxy
    links:
      - node1
      - node2
    ports:
      - "80:80"
      - "9000:9000"
    depends_on:
      - node1
      - node2
  memcached:
    image: memcached:1.6.9-alpine
    expose:
      - 11211
